"""init

Revision ID: 2aae692a3003
Revises: 
Create Date: 2026-05-27 22:56:09.710661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aae692a3003'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_credentials', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('candidate_molecules', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('candidate_molecules', 'task_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('compound_libraries', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('projects', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('screening_tasks', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('screening_tasks', 'target_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('screening_tasks', 'library_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('sdf_molecules', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.add_column('targets', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('targets', sa.Column('status', sa.String(length=20), nullable=True))
    op.alter_column('targets', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('targets', 'project_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('targets', 'structure_path',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('tool_configurations', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tool_configurations', 'id',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('targets', 'structure_path',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('targets', 'project_id',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('targets', 'id',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('targets', 'status')
    op.drop_column('targets', 'name')
    op.alter_column('sdf_molecules', 'id',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('screening_tasks', 'library_id',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('screening_tasks', 'target_id',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('screening_tasks', 'id',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('projects', 'id',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('compound_libraries', 'id',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('candidate_molecules', 'task_id',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('candidate_molecules', 'id',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('api_credentials', 'id',
               existing_type=sa.String(length=36),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    # ### end Alembic commands ###
