#!/usr/bin/env python3
"""Sync Hermes project home (.hermes) from project .env + CC-Switch current provider.

Reads ~/.cc-switch/cc-switch.db (current Claude provider) and merges env into
$PROJECT/.hermes/.env. Ensures .hermes/config.yaml exists (from template).

Does not print secrets. Never writes keys into committed YAML.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import sqlite3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CCSWITCH_DB = Path.home() / ".cc-switch" / "cc-switch.db"
DEFAULT_SETTINGS = Path.home() / ".cc-switch" / "settings.json"
TEMPLATE = ROOT / "config" / "hermes.config.yaml"
SOUL_TEMPLATE = ROOT / "config" / "SOUL.md"
PLATFORM_MD = ROOT / "config" / "platform" / "PLATFORM.md"
PLATFORM_CATALOG = ROOT / "config" / "platform" / "catalog.yaml"
SKIN_SRC = ROOT / "config" / "skins" / "edrug-scientist.yaml"
SKIN_NAME = "edrug-scientist"
PROVIDER_ENV_PREFIXES = ("ANTHROPIC_", "OPENAI_", "MASLD_LLM_")
PROVIDER_ENV_KEYS = {"CLAUDE_CODE_EFFORT_LEVEL"}


def _load_dotenv_file(path: Path) -> dict[str, str]:
    out: dict[str, str] = {}
    if not path.is_file():
        return out
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, val = line.partition("=")
        key = key.strip()
        val = val.strip().strip("'").strip('"')
        if key:
            out[key] = val
    return out


def _write_dotenv(path: Path, data: dict[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Auto-generated by scripts/sync_providers_from_ccswitch.py — do not commit",
        "# Hermes multi-provider credentials (HERMES_HOME=.hermes)",
        "",
    ]
    for key in sorted(data.keys()):
        lines.append(f"{key}={data[key]}")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")
    try:
        os.chmod(path, 0o600)
    except OSError:
        pass


def _strip_provider_env(data: dict[str, str]) -> dict[str, str]:
    return {
        key: value
        for key, value in data.items()
        if key not in PROVIDER_ENV_KEYS
        and not any(key.startswith(prefix) for prefix in PROVIDER_ENV_PREFIXES)
    }


def _claude_provider(
    db: Path,
    settings_path: Path,
    selector: str | None = None,
) -> dict | None:
    if not db.is_file():
        return None
    provider_id = None
    if not selector and settings_path.is_file():
        try:
            provider_id = json.loads(settings_path.read_text(encoding="utf-8")).get(
                "currentProviderClaude"
            )
        except json.JSONDecodeError:
            provider_id = None
    conn = sqlite3.connect(str(db))
    try:
        cur = conn.cursor()
        if selector:
            cur.execute(
                "SELECT id, name, settings_config, website_url FROM providers "
                "WHERE app_type='claude' AND (id=? OR lower(name)=lower(?)) LIMIT 1",
                (selector, selector),
            )
        elif provider_id:
            cur.execute(
                "SELECT id, name, settings_config, website_url FROM providers "
                "WHERE id=? AND app_type='claude'",
                (provider_id,),
            )
        else:
            cur.execute(
                "SELECT id, name, settings_config, website_url FROM providers "
                "WHERE app_type='claude' AND is_current=1 LIMIT 1"
            )
        row = cur.fetchone()
    finally:
        conn.close()
    if not row:
        return None
    pid, name, settings_config, website = row
    try:
        cfg = json.loads(settings_config)
    except json.JSONDecodeError:
        cfg = {}
    return {
        "id": pid,
        "name": name,
        "website_url": website,
        "env": dict(cfg.get("env") or {}),
        "model": cfg.get("model"),
    }


def _current_claude_provider(db: Path, settings_path: Path) -> dict | None:
    return _claude_provider(db, settings_path)


def _merge_from_ccswitch(
    env: dict[str, str],
    provider: dict,
    *,
    model_override: str | None = None,
) -> None:
    """Map Claude-Code-style CC-Switch env into Hermes + dual-wire keys."""
    src = provider.get("env") or {}
    for k, v in src.items():
        if v is not None and str(v).strip():
            env[str(k)] = str(v).strip()

    # Hermes anthropic resolver prefers ANTHROPIC_API_KEY / ANTHROPIC_TOKEN
    token = (
        env.get("ANTHROPIC_AUTH_TOKEN")
        or env.get("ANTHROPIC_API_KEY")
        or env.get("ANTHROPIC_TOKEN")
        or ""
    ).strip()
    if token:
        env["ANTHROPIC_AUTH_TOKEN"] = token
        env["ANTHROPIC_API_KEY"] = token
        env["ANTHROPIC_TOKEN"] = token
        env["OPENAI_API_KEY"] = token
        env["MASLD_LLM_API_KEY"] = token

    base = (env.get("ANTHROPIC_BASE_URL") or "").rstrip("/")
    if base:
        # OpenAI Coding Plan wire
        if base.endswith("/api/coding"):
            env["OPENAI_BASE_URL"] = base + "/v3"
            env["MASLD_LLM_BASE_URL"] = base + "/v3"
        elif "/api/coding/v3" in base:
            env["OPENAI_BASE_URL"] = base
            env["MASLD_LLM_BASE_URL"] = base

    model = (
        model_override
        or env.get("ANTHROPIC_MODEL")
        or env.get("MASLD_LLM_MODEL")
        or "ark-code-latest"
    )
    env["MASLD_LLM_MODEL"] = model
    env["ANTHROPIC_MODEL"] = model


def _ensure_plugin_enabled(data: dict) -> bool:
    """Ensure scientist_in_e_drug_lab is listed under plugins.enabled. Returns dirty."""
    data.setdefault("plugins", {})
    enabled = data["plugins"].setdefault("enabled", [])
    if isinstance(enabled, list) and "scientist_in_e_drug_lab" not in enabled:
        enabled.append("scientist_in_e_drug_lab")
        return True
    return False


def _ensure_edrug_skin(data: dict) -> bool:
    """Force display.skin to edrug-scientist. Returns dirty."""
    display = data.setdefault("display", {})
    if not isinstance(display, dict):
        data["display"] = {"skin": SKIN_NAME}
        return True
    if display.get("skin") != SKIN_NAME:
        display["skin"] = SKIN_NAME
        return True
    return False


def _sync_skin_file(hermes_home: Path) -> Path | None:
    """Copy project skin YAML into HERMES_HOME/skins/."""
    if not SKIN_SRC.is_file():
        return None
    dst_dir = hermes_home / "skins"
    dst_dir.mkdir(parents=True, exist_ok=True)
    dst = dst_dir / SKIN_SRC.name
    shutil.copy2(SKIN_SRC, dst)
    return dst


def _provider_slug(name: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", name.strip().lower()).strip("-")
    return slug or "ccswitch-claude"


def _ensure_config(
    hermes_home: Path,
    provider: dict | None,
    *,
    activate_selected: bool = False,
    context_length: int | None = None,
    model_override: str | None = None,
    configured_provider: str | None = None,
    reasoning_effort: str | None = None,
    prune_unlisted_providers: bool = False,
) -> Path:
    import yaml

    cfg_path = hermes_home / "config.yaml"
    if not cfg_path.exists():
        if not TEMPLATE.is_file():
            raise FileNotFoundError(f"Missing template: {TEMPLATE}")
        shutil.copy2(TEMPLATE, cfg_path)

    data = yaml.safe_load(cfg_path.read_text(encoding="utf-8")) or {}
    dirty = False

    if prune_unlisted_providers:
        template_data = yaml.safe_load(TEMPLATE.read_text(encoding="utf-8")) or {}
        allowed_providers = set((template_data.get("providers") or {}).keys())
        providers = data.setdefault("providers", {})
        if isinstance(providers, dict):
            for name in list(providers):
                if name not in allowed_providers:
                    providers.pop(name)
                    dirty = True

    # Optionally retarget default model from CC-Switch.
    if provider and provider.get("env"):
        model = (model_override or provider["env"].get("ANTHROPIC_MODEL") or "").strip()
        if model:
            data.setdefault("model", {})["default"] = model
            for name in ("volcengine-plan", "volcano-anthropic"):
                entry = (data.get("providers") or {}).get(name)
                if isinstance(entry, dict):
                    entry["default_model"] = model
                    entry.setdefault("models", {}).setdefault(model, {})
            dirty = True

        if activate_selected:
            env = provider["env"]
            base_url = (env.get("ANTHROPIC_BASE_URL") or "").strip().rstrip("/")
            if not model:
                raise ValueError(
                    f"CC-Switch provider {provider.get('name')!r} has no ANTHROPIC_MODEL"
                )
            if not base_url:
                raise ValueError(
                    f"CC-Switch provider {provider.get('name')!r} has no ANTHROPIC_BASE_URL"
                )

            metadata = {"context_length": context_length} if context_length else {}
            if base_url.endswith("/api/coding"):
                slug = "volcano-anthropic"
                selected_entries = {
                    "volcano-anthropic": {
                        "name": "Volcengine DeepSeek (Anthropic)",
                        "base_url": base_url,
                        "key_env": "ANTHROPIC_AUTH_TOKEN",
                        "api_mode": "anthropic_messages",
                        "default_model": model,
                        "models": {model: dict(metadata)},
                    },
                    "volcengine-plan": {
                        "name": "Volcengine DeepSeek (OpenAI)",
                        "base_url": base_url + "/v3",
                        "key_env": "OPENAI_API_KEY",
                        "api_mode": "chat_completions",
                        "default_model": model,
                        "models": {model: dict(metadata)},
                    },
                }
            else:
                slug = _provider_slug(str(provider.get("name") or ""))
                key_env = (
                    "ANTHROPIC_API_KEY"
                    if env.get("ANTHROPIC_API_KEY")
                    else "ANTHROPIC_AUTH_TOKEN"
                )
                selected_entries = {
                    slug: {
                        "name": str(provider.get("name") or slug),
                        "base_url": base_url,
                        "key_env": key_env,
                        "api_mode": "anthropic_messages",
                        "default_model": model,
                        "models": {model: dict(metadata)},
                    }
                }
            data.setdefault("providers", {}).update(selected_entries)
            model_config = data.setdefault("model", {})
            model_config.update({"provider": slug, "default": model})
            for stale_key in ("base_url", "api_mode", "api_key"):
                model_config.pop(stale_key, None)
            if context_length:
                model_config["context_length"] = context_length
            else:
                model_config.pop("context_length", None)
            dirty = True

    if configured_provider:
        providers = data.setdefault("providers", {})
        entry = providers.get(configured_provider)
        if not isinstance(entry, dict):
            template_data = yaml.safe_load(TEMPLATE.read_text(encoding="utf-8")) or {}
            template_entry = (template_data.get("providers") or {}).get(configured_provider)
            if not isinstance(template_entry, dict):
                raise ValueError(f"Configured Hermes provider not found: {configured_provider}")
            entry = dict(template_entry)
            providers[configured_provider] = entry
        model = (model_override or entry.get("default_model") or "").strip()
        if not model:
            raise ValueError(f"No model configured for Hermes provider: {configured_provider}")
        model_config = data.setdefault("model", {})
        model_config.update({"provider": configured_provider, "default": model})
        if context_length:
            model_config["context_length"] = context_length
        models = entry.setdefault("models", {})
        if isinstance(models, dict):
            metadata = models.setdefault(model, {})
            if context_length and isinstance(metadata, dict):
                metadata["context_length"] = context_length
        entry["default_model"] = model
        dirty = True

    if reasoning_effort:
        data.setdefault("agent", {})["reasoning_effort"] = reasoning_effort
        dirty = True

    if _ensure_plugin_enabled(data):
        dirty = True
    if _ensure_edrug_skin(data):
        dirty = True

    # Platform catalog pointer (alongside SOUL; does not change identity)
    platform = data.setdefault("platform", {})
    if not isinstance(platform, dict):
        data["platform"] = {}
        platform = data["platform"]
        dirty = True
    catalog_rel = "platform/catalog.yaml"
    if platform.get("catalog") != catalog_rel:
        platform["catalog"] = catalog_rel
        dirty = True
    if platform.get("overview") != "PLATFORM.md":
        platform["overview"] = "PLATFORM.md"
        dirty = True

    if dirty:
        cfg_path.write_text(
            yaml.safe_dump(data, sort_keys=False, allow_unicode=True),
            encoding="utf-8",
        )
    return cfg_path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--hermes-home",
        type=Path,
        default=ROOT / ".hermes",
        help="Project HERMES_HOME (default: <project>/.hermes)",
    )
    parser.add_argument("--ccswitch-db", type=Path, default=DEFAULT_CCSWITCH_DB)
    parser.add_argument("--ccswitch-settings", type=Path, default=DEFAULT_SETTINGS)
    parser.add_argument(
        "--ccswitch-provider",
        help="Select a Claude provider by exact CC-Switch name or id; otherwise use current",
    )
    parser.add_argument(
        "--context-length",
        type=int,
        help="Explicit Hermes context window for the selected model",
    )
    parser.add_argument(
        "--model",
        help="Override the CC-Switch ANTHROPIC_MODEL for this Hermes agent",
    )
    parser.add_argument(
        "--activate-provider",
        help="Activate an existing named Hermes provider without importing CC-Switch",
    )
    parser.add_argument(
        "--reasoning-effort",
        choices=("none", "minimal", "low", "medium", "high", "xhigh", "max", "ultra"),
        help="Persist the Hermes reasoning effort",
    )
    parser.add_argument(
        "--skip-ccswitch",
        action="store_true",
        help="Only sync from project .env (ignore CC-Switch DB)",
    )
    parser.add_argument(
        "--prune-unlisted-providers",
        action="store_true",
        help="Remove Hermes providers absent from the project template",
    )
    parser.add_argument(
        "--strip-provider-env",
        action="store_true",
        help="Exclude provider credentials inherited from the project .env",
    )
    args = parser.parse_args()

    hermes_home: Path = args.hermes_home
    hermes_home.mkdir(parents=True, exist_ok=True)

    env = _load_dotenv_file(ROOT / ".env")
    if args.strip_provider_env:
        env = _strip_provider_env(env)
    provider = None
    if not args.skip_ccswitch:
        provider = _claude_provider(
            args.ccswitch_db,
            args.ccswitch_settings,
            args.ccswitch_provider,
        )
        if provider:
            _merge_from_ccswitch(env, provider, model_override=args.model)
            source = "selected" if args.ccswitch_provider else "current"
            print(f"CC-Switch {source}: {provider.get('name')} ({provider.get('id')})")
        elif args.ccswitch_provider:
            raise SystemExit(
                f"CC-Switch Claude provider not found: {args.ccswitch_provider}"
            )
        else:
            print("CC-Switch: no current Claude provider found; using project .env only")

    # Competition eval flag for masld tools
    env.setdefault("MASLD_COMPETITION_EVAL_MODE", "true")

    cfg_path = _ensure_config(
        hermes_home,
        provider,
        activate_selected=bool(args.ccswitch_provider),
        context_length=args.context_length,
        model_override=args.model,
        configured_provider=args.activate_provider,
        reasoning_effort=args.reasoning_effort,
        prune_unlisted_providers=args.prune_unlisted_providers,
    )
    env_path = hermes_home / ".env"
    _write_dotenv(env_path, env)

    soul_dst = hermes_home / "SOUL.md"
    if SOUL_TEMPLATE.is_file():
        shutil.copy2(SOUL_TEMPLATE, soul_dst)
        print(f"Wrote {soul_dst} (from config/SOUL.md)")

    # Platform knowledge (parallel to SOUL — does not replace identity)
    if PLATFORM_MD.is_file():
        shutil.copy2(PLATFORM_MD, hermes_home / "PLATFORM.md")
        print(f"Wrote {hermes_home / 'PLATFORM.md'}")
    if PLATFORM_CATALOG.is_file():
        plat_dir = hermes_home / "platform"
        plat_dir.mkdir(parents=True, exist_ok=True)
        shutil.copy2(PLATFORM_CATALOG, plat_dir / "catalog.yaml")
        shutil.copy2(PLATFORM_MD, plat_dir / "PLATFORM.md")
        print(f"Wrote {plat_dir / 'catalog.yaml'}")

    skin_dst = _sync_skin_file(hermes_home)
    if skin_dst:
        print(f"Wrote {skin_dst} (skin={SKIN_NAME})")

    has_key = bool(
        env.get("OPENAI_API_KEY")
        or env.get("ANTHROPIC_AUTH_TOKEN")
        or env.get("ANTHROPIC_API_KEY")
        or os.environ.get("OPENAI_API_KEY")
        or os.environ.get("ANTHROPIC_AUTH_TOKEN")
        or os.environ.get("ANTHROPIC_API_KEY")
    )
    print(f"Wrote {cfg_path}")
    print(f"Wrote {env_path} (keys_present={has_key}, n_vars={len(env)})")
    print(f"HERMES_HOME={hermes_home}")
    return 0 if has_key else 1


if __name__ == "__main__":
    raise SystemExit(main())
